backend:
  name: github
  repo: lntuandat/CMSNhom10
  branch: main 
  auth_type: pkce 
  app_id: Ov23ct6LX9i2UpRbCOnM
  base_url: https://cms-nhom10.vercel.app/
  
  cms_label_prefix: Vercel

media_folder: "images/uploads"
public_folder: "/images/uploads" 

collections:
  - name: "pages"
    label: "Pages"
    files:
      - name: "index"
        label: "Home Page"
        file: "index.html"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Content", name: "content", widget: "text" }
      
