backend:
  name: github
  repo: lntuandat/CMSNhom10
  branch: main
  auth_type: pkce
  app_id: ${GITHUB_CLIENT_ID}
  client_secret: ${GITHUB_CLIENT_SECRET}  # Tham chiếu tới biến môi trường
  base_url: https://cms-nhom10.vercel.app/
  cms_label_prefix: Vercel

media_folder: "images/uploads" # Thư mục lưu trữ hình ảnh trên repo
public_folder: "/images/uploads" # Thư mục hình ảnh công khai

collections:
  - name: "pages"
    label: "Pages"
    files:
      - name: "index"
        label: "Home Page"
        file: "index.html"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Content", name: "content", widget: "text" }
      